[2024-06-16T14:26:24.307+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-16T14:26:24.346+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: my_dag.accurate manual__2024-06-16T14:25:47.010675+00:00 [queued]>
[2024-06-16T14:26:24.365+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: my_dag.accurate manual__2024-06-16T14:25:47.010675+00:00 [queued]>
[2024-06-16T14:26:24.366+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-06-16T14:26:24.390+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): accurate> on 2024-06-16 14:25:47.010675+00:00
[2024-06-16T14:26:24.401+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=242) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-06-16T14:26:24.405+0000] {standard_task_runner.py:63} INFO - Started process 244 to run task
[2024-06-16T14:26:24.404+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'my_dag', 'accurate', 'manual__2024-06-16T14:25:47.010675+00:00', '--job-id', '128', '--raw', '--subdir', 'DAGS_FOLDER/my_dag.py', '--cfg-path', '/tmp/tmp46hjsk2v']
[2024-06-16T14:26:24.409+0000] {standard_task_runner.py:91} INFO - Job 128: Subtask accurate
[2024-06-16T14:26:24.483+0000] {task_command.py:426} INFO - Running <TaskInstance: my_dag.accurate manual__2024-06-16T14:25:47.010675+00:00 [running]> on host 3ee39c4edaab
[2024-06-16T14:26:24.592+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='my_dag' AIRFLOW_CTX_TASK_ID='accurate' AIRFLOW_CTX_EXECUTION_DATE='2024-06-16T14:25:47.010675+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-16T14:25:47.010675+00:00'
[2024-06-16T14:26:24.595+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-16T14:26:24.598+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-06-16T14:26:24.602+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', "echo 'accurate'"]
[2024-06-16T14:26:24.620+0000] {subprocess.py:86} INFO - Output:
[2024-06-16T14:26:24.628+0000] {subprocess.py:93} INFO - accurate
[2024-06-16T14:26:24.629+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2024-06-16T14:26:24.632+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-16T14:26:24.663+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=my_dag, task_id=accurate, run_id=manual__2024-06-16T14:25:47.010675+00:00, execution_date=20240616T142547, start_date=20240616T142624, end_date=20240616T142624
[2024-06-16T14:26:24.700+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-06-16T14:26:24.727+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-16T14:26:24.729+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
